mysql:
  url: jdbc:mysql://rm-2zeu4x1450e1g7xl75o.mysql.rds.aliyuncs.com:3306/aimin?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  username: root
  password: kingks()16
  author: zhage
  packageParent: com.oimc.aimin.auth
